import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Books App</h1>

        <div className={styles.grid}>
          <a href="/libros" data-cy="link-to-books" className={styles.card}>
            Book List Libros
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/izaack89"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" German Ramirez "}
        </a>
      </footer>
    </div>
  );
}
